# Single akun
# reformat di : sub.bonds.id
# Akun Vless CF (No UDP)
# =========== PROXY ACCOUNT ===========
proxies:
  - name: SG1-XUTS 🇸🇬
    server: 104.18.214.235
    port: 443
    type: vless
    uuid: fccdaaae-af39-41a7-9fde-fd32a48278cf
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: ava.game.naver.com.aio.skibidicx.web.id
    network: ws
    ws-opts:
      path: /SG1
      headers:
        Host: ava.game.naver.com.aio.skibidicx.web.id
    udp: true
  - name: SG2-XUTS 🇸🇬
    server: 104.18.214.235
    port: 443
    type: vless
    uuid: aaaaaaa1-bbbb-4ccc-accc-eeeeeeeeeee1
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: ava.game.naver.com.free.vpn-wuss.BIZ.id
    network: ws
    ws-opts:
      path: /Free/TG-at-BitzBlack/138.2.74.219-28616
      headers:
        Host: ava.game.naver.com.free.vpn-wuss.BIZ.id
    udp: true
  - name: SG1-AVA1 🇸🇬
    server: 104.18.214.235
    port: 443
    type: vless
    uuid: fccdaaae-af39-41a7-9fde-fd32a48278cf
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: ava.game.naver.com.aio.skibidicx.web.id
    network: ws
    ws-opts:
      path: /SG1
      headers:
        Host: ava.game.naver.com.aio.skibidicx.web.id
    udp: true
  - name: SG2-AVA 🇸🇬
    server: 104.18.214.235
    port: 443
    type: vless
    uuid: aaaaaaa1-bbbb-4ccc-accc-eeeeeeeeeee1
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: ava.game.naver.com.free.bansos.BIZ.id
    network: ws
    ws-opts:
      path: /Free/TG-at-BitzBlack/129.226.150.167-443
      headers:
        Host: ava.game.naver.com.free.bansos.BIZ.id
    udp: true